# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - mjresume-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint or test (optional)
        run: |
          echo "Run linting or testing here if needed"
          # e.g., flake8 . or pytest

      - name: Prepare Azure Function artifact
        run: |
          mkdir -p artifact
          cp -r update_visit_count function_app.py host.json requirements.txt artifact/

      - name: Upload Azure Function artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: artifact/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: List current directory
        run: ls -l
        
      - name: List all files recursively
        run: ls -R

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: .
